### ISSUE TITLE
sendpass not implemented

### ISSUE THREAD

**Issue by joker234** [robustirc/robustirc#147]
Please implement sendpass so that Users can register and don't have to choose a new nickname or wait for the nick to expire.

Or is there another possiblity to regain control of an irc user account?

**Comment by stapelberg** [comment]
Technical detail upfront: the services support email, it’s just not enabled.

I thought about this for a while now, and came to the conclusion that I don’t want to be responsible for sending automated emails for various reasons.

In the event that users screw up their registration (which has happened only once or twice, AFAIK), they can escalate to one of the network operators — currently just me — and get their registration dropped.

If this turns out to not scale well in the longer term, we can appoint additional service operators.
